# Generated by Django 5.1.5 on 2025-02-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userupload',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
