# Generated by Django 5.1.5 on 2025-02-05 00:19

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userupload_error_message_userupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='batch_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='nifti_file',
            field=models.FileField(blank=True, help_text='Upload NIfTI files only (.nii or .nii.gz)', null=True, upload_to='uploads/', validators=[api.models.validate_nifti]),
        ),
    ]
