# Generated by Django 5.1.5 on 2025-02-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userupload_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploaded', max_length=100),
        ),
    ]
