# Generated by Django 5.1.7 on 2025-03-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='report_generated',
            field=models.BooleanField(default=False),
        ),
    ]
