# Generated by Django 5.1.7 on 2025-03-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userupload_report_generated'),
    ]

    operations = [
    ]
