# Generated by Django 5.1.7 on 2025-03-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userupload_report_generated'),
        ('api', '0006_userupload_report_generated_existing'),
    ]

    operations = [
    ]
